# Name of github action:
name: Eleventy-to-GH-Pages

# Triggers on a push to a branch or manually (workflow_dispatch)
on:
  push: 
    branches: [ "main" ]
  workflow_dispatch:  # manually (useful for debugging)

# what should be done
jobs:
  # we have only one stage and we name it 'build'
  build:
    runs-on: ubuntu-latest  # Docker image used to run the steps below

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Branch checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install 11ty dependencies from package.json and build
        run: npm ci
        run: npm npx @11ty/eleventy

      
      - name: deploy  # deploy contents of output folder to the branch gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Needed to Create self-gen token to push files to repsitory
          publish_dir: ./docs  # Eleventy default output folder: _site
